CREATE TABLE buyer
(
    ID	BIGSERIAL	NOT NULL PRIMARY KEY,
    NAME	VARCHAR(255)	NOT NULL,
    ORDERS_ID INTEGER
        REFERENCES ORDERS (ID)
);

CREATE TABLE ORDERS
(
    ID               BIGSERIAL      NOT NULL PRIMARY KEY,
    PRODUCT_LIST            VARCHAR(255)   NOT NULL,
    COST             DECIMAL(10, 2) NOT NULL
);